### ISSUE TITLE
Requires jenssegers/optimus - Not mentioned in instructions

### ISSUE THREAD

**Issue by CaffeinatedTech** [delight-im/PHP-IDs#1]
Discovered that it requires jenssegers/optimus or it throws an error.  Should probably list that as a requirement in the readme.

**Comment by ocram** [comment]
You're right, of course. Sorry for that!

This was just because using Composer is actually the recommended way to install this library. The notes on manual installation were still in the README, but shouldn't be there anymore, since there's really no reason why one shouldn't use Composer. Sure, Composer requires some short introduction and reading how to install and use it, but that's it. The benefits, not specifically for this library but in general, are huge!

Thus the notes on manual installation have been removed in https://github.com/delight-im/PHP-IDs/commit/b2ec0a9ae23c00c2397574f82eaf5bc49e010796

Thanks for the hint!
